### ISSUE TITLE
Shortcut to Open URLs

### ISSUE THREAD

**Issue by grebenyuksv-preply** [differentmatt/vscode-copy-github-url#19]
Dear contributors, thanks for this awesome plugin, I'm gonna stick to it because it supports Git worktrees and `master` URLs, unlike the one VSCode folks [mention on their website](https://code.visualstudio.com/docs/editor/github).

Is there a chance you could add shortcuts to actually open those URLs in the browser?

I could contribute myself if you don't have time for this, but decided to ask you first.

**Comment by differentmatt** [comment]
Thanks for reaching out.  I would be happy to review any contributions you want to make.
________________________________
From: Sergii Grebeniuk ***@***.***>
Sent: Tuesday, July 20, 2021 7:46:19 AM
To: differentmatt/vscode-copy-github-url ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [differentmatt/vscode-copy-github-url] Shortcut to Open URLs (#19)


Dear contributors, thanks for this awesome plugin, I'm gonna stick to it because it supports Git worktrees and master URLs, unlike the one VSCode folks mention on their website<https://code.visualstudio.com/docs/editor/github>.

Is there a chance you could add shortcuts to actually open those URLs in the browser?

I could contribute myself if you don't have time for this, but decided to ask you first.

**Comment by grebenyuksv-preply** [comment]
Hm, it actually stopped working for me in worktrees with `(Copy GitHub URL) Error: .git/HEAD does not exist.` error, which is why I'll have to stop using the plugin :( Closing the issue, sorry for disturbing

**Comment by differentmatt** [comment]
Sorry to hear this stopped working for you.  We'll have to look into this issue.  Thanks!
________________________________
